name: hls4ml_frame_grabber
channels:
  - conda-forge
dependencies:
  - python=3.8.13=ha86cf86_0_cpython
  - ipykernel=6.13.0=py38h7f3c49e_0
  - ipython=8.2.0=py38h578d9bd_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - psutil=5.9.0=py38h0a891b7_1
  - pip:
    - hls4ml==0.8.1
    - keras==2.8.0
    - numpy==1.22.3
    - matplotlib==3.3.4
    - python-utils==3.1.0
    - pandas==1.4.2
    - opencv-python==4.5.5.64
    - qkeras==0.9.0
    - scipy==1.8.0
    - seaborn==0.12.2
    - sidpy==0.11.2
    - pydot==1.4.2
    - graphviz==0.20.1
    - sympy==1.12.1
    - protobuf==3.20.0
    - tensorflow==2.8.0
    - torch==1.11.0
    - torchaudio==0.11.0
    - torchvision==0.12.0
